### ISSUE TITLE
First paragraph of Readme

### ISSUE THREAD

**Issue by HarendraSingh22** [codeuino/website-www.codeuino.org#31]
The first paragraph of the Readme is bad ! 

It isn't apt if we are calling codeuino an organisation, it seems like a readme of some kid's personal project.

Also is saying that the social platform being made is similar to Facebook a good thing? When facebook exists why is this being made???????? Add there what's unique about this one.

**Comment by aryan-harsh** [comment]
@Saichethan @jaskirat2000 @HarendraSingh22  is the issue still open, I could contribute

**Comment by jaskirat2000** [comment]
Yes it is open you can work on it and while you work tag a label with
working in it
On 29-Jun-2018 1:18 AM, "Harsh Aryan" <notifications@github.com> wrote:

@Saichethan <https://github.com/Saichethan> @jaskirat2000
<https://github.com/jaskirat2000> @HarendraSingh22
<https://github.com/HarendraSingh22> is the issue still open, I could
contribute

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/codeuino/website-www.codeuino.org/issues/31#issuecomment-401152100>,
or mute the thread

**Comment by im-gozmit** [comment]
@jaskirat2000 I have found so many issues got solved and still open. Please check all of them and close the ones which are solved, like this one.
